CREATE TABLE TRS_USERS(
USERNAME VARCHAR2(50) PRIMARY KEY,
PASSWORD VARCHAR2(50),
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
BALANCE NUMBER(*,2),
ACCOUNT_TYPE VARCHAR2(50));

CREATE TABLE FORMS(
F_ID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(50),
E_Type VARCHAR2(50),
E_COST NUMBER (*,2),
E_GRADE_TYPE VARCHAR2(50),
E_STARTD DATE,
R_AMT NUMBER(*,2),
R_ADDITIONAL NUMBER (*,2),
F_GRADE VARCHAR2(50),
F_STATUS VARCHAR2(50)
);

CREATE TABLE PROCESSING(
USERNAME VARCHAR2(50),
F_ID INTEGER,
DIR_SUP_APPROVE VARCHAR2(50),
DEPT_HEAD_APPROVE VARCHAR2(50),
BENCO_APPROVE VARCHAR2(50),
DIR_SUP_REASON VARCHAR2(50),
DEPT_HEAD_REASON VARCHAR2(50),
BENCO_REASON VARCHAR2(50)
);


ALTER TABLE PROCESSING
ADD CONSTRAINT FK_PROCESSING_TRS_USERS
FOREIGN KEY(USERNAME) REFERENCES TRS_USERS(USERNAME);

ALTER TABLE PROCESSING
ADD CONSTRAINT FK_PROCESSING_FORMS
FOREIGN KEY(F_ID) REFERENCES FORMS(F_ID);


--FORM STATUSES--
    --Not Accepted
    --Not Accepted (Urgent)
    --Processing
    --Awarded
    --Not Awarded

ALTER TABLE FORMS
ADD CONSTRAINT FK_FORMS_TRS_USERS
FOREIGN KEY(USERNAME) REFERENCES TRS_USERS(USERNAME);

DROP SEQUENCE SEQ_F_ID;
DROP SEQUENCE SEQ_F_ID2;
CREATE SEQUENCE SEQ_F_ID;
CREATE SEQUENCE SEQ_F_ID2;

UPDATE PROCESSING SET DIR_SUP_APPROVE = 'Accepted', DEPT_HEAD_APPROVE = 'Accepted' WHERE F_ID = 22;








commit;




